<?php
/**
* @file
* Módulo para definir bloques
* Este módulo crea un bloque con nodos publicados que se activa en el lateral derecho
*/

/**
 * Implements hook_install().
 */
function blocks_forcontu_install() {
  // Obtenemos el tema activo
  $default_theme = variable_get('theme_default', 'bartik');
  _block_rehash($default_theme);
}

/**
 * Implements hook_uninstall().
 */
function blocks_forcontu_uninstall() {
  
}